name: Docker Image CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${GITHUB_REPOSITORY}/release:${RELEASE_VERSION}
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      
    - name: Push
      run: |
        echo "${GITHUB_PACKAGE_REGISTRY_TOKEN}" | docker login docker.pkg.github.com --username fdns --password-stdin
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/release:${RELEASE_VERSION}
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
